#ifndef PRIMITIVE_H
#define PRIMITIVE_H

enum primitive_type {
	PRIMITIVE_TYPE_RECTANGLE,
	PRIMITIVE_TYPE_TEXT,
	PRIMITIVE_TYPE_ARC,
	PRIMITIVE_TYPE_BITMAP,
	PRIMITIVE_TYPE_IMAGE,
	PRIMITIVE_TYPE_LINE,
	PRIMITIVE_TYPE_OVAL,
	PRIMITIVE_TYPE_POLYGON,
	PRIMITIVE_TYPE_WINDOW,
};

struct primitive {
	unsigned int type;
};

#endif
